version: '3.8'

services:
  db:
    image: postgres:16
    container_name: pg-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: vinh2711
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  webapi:
    build: .
    container_name: my-webapi
    depends_on:
      - db
    environment:
      # ✅ Sửa Host thành 'db'
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=postgres;Username=postgres;Password=vinh2711"
      ASPNETCORE_URLS: "http://+:80"
    ports:
      - "5000:80"

volumes:
  db_data:
